[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["echo '=== Files in public during build ===' && ls -la public/ && echo '=== End of file list ==='"]

[start]
cmd = "node server.js"
